metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.kibana:
  host: "kibana:5601"

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]

processors:
  - add_host_metadata: ~
  - add_docker_metadata: ~

metricbeat.modules:
  - module: docker
    metricsets:
      - container
      - cpu
      - memory
      - network
      - diskio
    hosts: ["unix:///var/run/docker.sock"]
    period: 10s
    enabled: true